### ISSUE TITLE
Help Me 

### ISSUE THREAD

**Issue by daner5208** [FRNathan13/WarfaceEmulator#1]
video pls youtube pls help me

tutorial video help me ?

**Comment by daner5208** [comment]
@FRNathan13

**Comment by FRNathan13** [comment]
?

**Comment by FRNathan13** [comment]
Sill in development soon video 👍 explaining all

**Comment by FRNathan13** [comment]
I recommend you follow this repository: https://github.com/FRNathan13/warface-emulator/ made in NodeJS (more simple)

**Comment by FRNathan13** [comment]
@daner5208 Check updated repo.
